hmpps-auth:
  url: "http://localhost:8090/auth"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

general-ledger-api:
  url: ${GENERAL_LEDGER_API_URL:http://localhost:8081}
  client:
    id: ${GENERAL_LEDGER_API_CLIENT_ID:hmpps-prisoner-finance-general-ledger-api}
    secret: ${GENERAL_LEDGER_API_CLIENT_SECRET:clientsecret}

holds-api:
  url: ${HOLDS_API_URL:http://localhost:8082}
  client:
    id: ${HOLDS_API_CLIENT_ID:hmpps-prisoner-finance-holds-api-1}
    secret: ${HOLDS_API_CLIENT_SECRET:clientsecret}

advances-api:
  url: ${ADVANCES_API_URL:http://localhost:8083}
  client:
    id: ${ADVANCES_API_CLIENT_ID:hmpps-prisoner-finance-advances-api-1}
    secret: ${ADVANCES_API_CLIENT_SECRET:clientsecret}