spring:
  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:postgresql://localhost:5432/nomis_sync?sslmode=prefer'
    username: postgres
    password: postgres

hmpps-auth:
  url: "http://localhost:8090/auth"

general-ledger-api:
  url: http://localhost:8084
  client:
    id: hmpps-prisoner-finance-general-ledger-api
    secret: clientsecret

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true