INSERT INTO account_code_lookup (account_code, name, classification, posting_type) VALUES
                                                                                       (1000, 'ASSETS', 'Asset', 'DR'),
                                                                                       (1100, 'Cash On Hand', 'Asset', 'DR'),
                                                                                       (1500, 'Accounts Receivable', 'Asset', 'DR'),
                                                                                       (2000, 'LIABILITIES', 'Liability', 'CR'),
                                                                                       (2100, 'Prisoner Accounts', 'Liability', 'CR'),
                                                                                       (2500, 'Prisoner Accounts Payable', 'Liability', 'CR'),
                                                                                       (3000, 'RECEIPTS', 'Receipt', 'CR'),
                                                                                       (4000, 'DISBURSEMENTS', 'Disbursement', 'DR'),
                                                                                       (10000, 'ASSETS', 'Asset', 'DR'),
                                                                                       (11000, 'Cash Accounts', 'Asset', 'DR'),
                                                                                       (20000, 'LIABILITIES', 'Liability', 'CR'),
                                                                                       (21000, 'Offender Accounts', 'Liability', 'CR'),
                                                                                       (25000, 'Accounts Payable', 'Liability', 'CR'),
                                                                                       (70000, 'OVERAGES', 'Receipt', 'CR'),
                                                                                       (71000, 'To Record Overages', 'Receipt', 'CR'),
                                                                                       (80000, 'SHORTAGES', 'Disbursement', 'DR'),
                                                                                       (81000, 'To Record Shortages', 'Disbursement', 'DR'),
                                                                                       (25040, 'XXX', 'Liability', 'CR'),
                                                                                       (25050, 'XXXX', 'Liability', 'CR'),
                                                                                       (25060, 'XXXX', 'Liability', 'CR'),
                                                                                       (25070, 'XXXX', 'Liability', 'CR'),
                                                                                       (25080, 'XXXX', 'Liability', 'CR'),
                                                                                       (25090, 'XXXX', 'Liability', 'CR'),
                                                                                       (25100, 'XXXX', 'Liability', 'CR'),
                                                                                       (25110, 'XXXX', 'Liability', 'CR'),
                                                                                       (25120, 'XXXX', 'Liability', 'CR'),
                                                                                       (25130, 'XXXX', 'Liability', 'CR'),
                                                                                       (25140, 'XXXX', 'Liability', 'CR'),
                                                                                       (25150, 'XXXX', 'Liability', 'CR'),
                                                                                       (25160, 'XXXX', 'Liability', 'CR'),
                                                                                       (25170, 'XXXX', 'Liability', 'CR'),
                                                                                       (25171, 'XXXXX', 'Liability', 'CR'),
                                                                                       (25172, 'XXXX', 'Liability', 'CR'),
                                                                                       (25180, 'XXXX', 'Liability', 'CR'),
                                                                                       (25190, 'XXXX', 'Liability', 'CR'),
                                                                                       (25200, 'XXXX', 'Liability', 'CR'),
                                                                                       (25210, 'XXXX', 'Liability', 'CR'),
                                                                                       (25230, 'XXXX', 'Liability', 'CR'),
                                                                                       (25240, 'XXXX', 'Liability', 'CR'),
                                                                                       (25260, 'XXXX', 'Liability', 'CR'),
                                                                                       (25270, 'XXXX', 'Liability', 'CR'),
                                                                                       (25280, 'XXXX', 'Liability', 'CR'),
                                                                                       (25290, 'XXXX', 'Liability', 'CR'),
                                                                                       (25211, 'XXXX', 'Liability', 'CR'),
                                                                                       (25212, 'XXXX', 'Liability', 'CR'),
                                                                                       (25213, 'XXXX', 'Liability', 'CR'),
                                                                                       (71020, 'XXXX', 'Receipt', 'CR'),
                                                                                       (81020, 'XXXX', 'Disbursement', 'DR');