CREATE TABLE advance_mapping
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    legacy_payment_profile_Id     BIGINT                                  NOT NULL,
    advance_uuid                  UUID                                    NOT NULL,
    CONSTRAINT pk_advance_mapping PRIMARY KEY (id)
);

ALTER TABLE advance_mapping
    ADD CONSTRAINT uc_advance_mapping_advance_uuid UNIQUE (advance_uuid);

ALTER TABLE advance_mapping
    ADD CONSTRAINT uc_advance_mapping_legacy_payment_profile_id UNIQUE (legacy_payment_profile_Id);

CREATE INDEX idx_advance_mapping_legacy_payment_profile_id ON advance_mapping (legacy_payment_profile_Id);