CREATE TABLE public.general_ledger_transaction_mapping
(
    id                      bigint generated by default as identity
        primary key,
    legacy_transaction_id   bigint                   not null,
    entry_sequence          integer                  not null,
    gl_transaction_uuid     uuid                     not null,
    created_at              timestamp with time zone not null default now(),

    constraint uq_gl_transaction_mapping_legacy_item
        unique (legacy_transaction_id, entry_sequence)
);

CREATE INDEX idx_gl_transaction_mapping_legacy_id
    on public.general_ledger_transaction_mapping (legacy_transaction_id);