CREATE TABLE holds_mapping
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    legacy_hold_number BIGINT                                  NOT NULL,
    holds_uuid         UUID                                    NOT NULL,
    CONSTRAINT pk_holds_mapping PRIMARY KEY (id)
);

ALTER TABLE holds_mapping
    ADD CONSTRAINT uc_holds_mapping_holds_uuid UNIQUE (holds_uuid);

ALTER TABLE holds_mapping
    ADD CONSTRAINT uc_holds_mapping_legacy_hold_number UNIQUE (legacy_hold_number);

CREATE INDEX idx_holds_mapping_legacy_hold_number ON holds_mapping (legacy_hold_number);