package uk.gov.justice.digital.hmpps.prisonerfinancepocapi.models.sync

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import jakarta.validation.constraints.Size
import java.time.LocalDateTime
import java.util.UUID

@Schema(description = "A response containing a general ledger transaction")
data class SyncGeneralLedgerTransactionResponse(

  @field:Schema(
    description = "The unique UUID generated by the **finance system** for the synchronized transaction. This is the internal identifier for the created or updated record.",
    example = "f1e2d3c4-b5a6-9876-5432-10fedcba9876",
    required = true,
  )
  var synchronizedTransactionId: UUID,

  @field:Schema(
    description = "The legacy ID of the transaction from the source system. This is only present if the transaction was originally generated by the legacy system.",
    example = "123456",
    required = false,
  )
  var legacyTransactionId: Long?,

  @field:Schema(description = "A description of the general ledger transaction.", example = "General Ledger Account Transfer", required = true)
  val description: String,

  @field:Schema(description = "An optional reference number for the transaction.", example = "REF12345", nullable = true)
  val reference: String?,

  @field:Schema(description = "The ID of the caseload associated with the transaction.", example = "GMI", required = true)
  val caseloadId: String,

  @field:Schema(description = "The transaction type", example = "GJ", required = true)
  val transactionType: String,

  @field:Schema(description = "The full timestamp of the transaction (ISO 8601).", example = "2011-09-30T09:08:08.671682", required = true)
  val transactionTimestamp: LocalDateTime,

  @field:Schema(
    description = "The date and time the transaction was created.",
    example = "2024-06-18T14:30:00.123456",
  )
  val createdAt: LocalDateTime,

  @field:Schema(
    description = "The user ID of the person who created the transaction in the source system.",
    example = "JD12345",
  )
  @field:Size(min = 1, max = 32, message = "Created by must be supplied and be <= 32 characters")
  val createdBy: String,

  @field:Schema(
    description = "The display name of the person who created the transaction.",
    example = "J Doe",
  )
  @field:Size(min = 1, max = 255, message = "Created by display name must be supplied and be <= 255 characters")
  val createdByDisplayName: String,

  @field:Schema(
    description = "The date and time the transaction was last modified. Only provided if the transaction has been modified since creation. (ISO 8601 format with offset)",
    example = "2022-07-15T23:03:01.123456",
  )
  val lastModifiedAt: LocalDateTime?,

  @field:Schema(
    description = "The user ID of the person who last modified the transaction. Required if lastModifiedAt has been supplied.",
    example = "AB11DZ",
  )
  @field:Size(max = 32, message = "Last modified by must be <= 32 characters")
  val lastModifiedBy: String?,

  @field:Schema(
    description = "The displayable name of the person who last modified the transaction. Required if lastModifiedAt has been supplied.",
    example = "U Dated",
  )
  @field:Size(max = 255, message = "Last modified by display name must be <= 255 characters")
  val lastModifiedByDisplayName: String?,

  @field:Schema(description = "A list of general ledger entries associated with this general ledger transaction.", required = true)
  @field:Valid
  val generalLedgerEntries: List<GeneralLedgerEntry>,
)
